config/routes.rb
CroonStar::Application.routes.draw do
  get "croons/listen/:id" => 'croons#listen'

  resources :tropo_recordings, :only => [:create]

  post "tropo_sessions/create"
  post "tropo_sessions/start_recording"
  post "tropo_sessions/processing"
  post "tropo_sessions/hangup"

  resources :croons, :only => [:index, :create, :show, :update]

  root :to => "croons#index"

end

app/models/croon.rb
class Croon
  include Mongoid::Document
  include Mongoid::Timestamps
  mount_uploader :recording, RecordingUploader

  validates_presence_of :phone_number
  validates_length_of :phone_number, :is => 10, :message => "must contain 10 digits"
  before_save :truncate_and_immute_crooner

  field :phone_number
  field :vote_count, :type => Integer, :default => 0
  field :crooner
  field :status, :default => "initialized"
  field :hangup, :type => Boolean
  referenced_in :song

  def truncate_and_immute_crooner()
    if self.crooner_was
      self.crooner = self.crooner_was
    else
      self.crooner = self.crooner.try(:first, 25)
    end
  end

  def song_attributes=(song_attributes)
    self.song = Song.criteria.id(song_attributes[:id]).first
  end

  def before_validation_on_create
    self.phone_number = phone_number.gsub(/[^0-9]/, "")
  end
end

app/models/song.rb
class Song
  include Mongoid::Document

  field :lyrics
  field :url
  field :title
  field :artist
  references_many :croons
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/croons_controller.rb
class CroonsController < ApplicationController
  def index
    @songs = Song.all
    page = params[:page] || 1
    @croons = Croon.where(:recording_filename.exists => true).order_by(:time_stamps.desc).paginate(:page => page, :per_page => 10)
    @croon = Croon.new
  end

  def create
    @croon = Croon.new(params[:croon])
    if @croon.save
      AwesomeHTTP.get("http://api.tropo.com/1.0/sessions?action=create&token=#{TROPO_APP_TOKEN}", :croon_id => @croon.id)
      redirect_to croon_url(@croon)
    else
      @songs = Song.all
      @croons = Croon.all
      render :index
    end
  end

  def show
    @croon = Croon.criteria.id(params[:id]).first
  end

  def update
    @croon = Croon.criteria.id(params[:id]).first
    puts params
    @croon.update_attributes(params[:croon])
    render :show
  end
end

app/controllers/tropo_recordings_controller.rb
class TropoRecordingsController < ApplicationController
  protect_from_forgery :except => [:create]

  def create
    @croon = Croon.criteria.id(params[:croon_id]).first
    @croon.recording = params[:filename]
    @croon.status = "complete"
    if @croon.save
      render :json => {:success => true}.to_json
    else
      render :json => {:success => false}.to_json
    end
  end

end

app/controllers/tropo_sessions_controller.rb
class TropoSessionsController < ApplicationController
  before_filter :find_croon
  def create
    @croon.update_attributes(:status => "calling")
    tropo = Tropo::Generator.new
    tropo.call :to => 'tel:+1' + @croon.phone_number
    tropo.on :event => "hangup", :next => "/tropo_sessions/hangup.json?croon_id=#{@croon.id}"
    tropo.on :event => "continue", :next => "/tropo_sessions/start_recording.json?croon_id=#{@croon.id}"
    tropo.ask({
      :name    => 'ready',
      :attempts => 5,
      :bargein => true,
      :timeout => 30,
      :require => 'true' }) do
        say     :value => 'Hello! Press 1 when your are ready to start singing. When you are finished, be sure to press 9 before haning up or your recording will not be saved.'
        choices :terminator => '1', :mode => "dtmf"
    end

    render :json => tropo.response
  end

  def start_recording
    @croon.update_attributes(:status => "recording")
    tropo = Tropo::Generator.new
    tropo.on :event => "hangup", :next => "/tropo_sessions/hangup.json?croon_id=#{@croon.id}" # processing.json if tropo fixes bug
    tropo.on :event => "continue", :next => "/tropo_sessions/processing.json?croon_id=#{@croon.id}"
    tropo.start_recording :url => "#{DOMAIN}/tropo_recordings.json?croon_id=#{@croon.id}", :format => "audio/wav"
    tropo.ask({
      :name    => 'done',
      :attempts => 1,
      :bargein => true,
      :timeout => 300,
      :require => 'false' }) do
        say     :value => 'Hello! Press 9 when you are done recording'
        choices :terminator => '9', :mode => "dtmf"
    end
    tropo.say @croon.song.url
    tropo.stop_recording


    render :json => tropo.response
  end

  def processing
    @croon.update_attributes(:status => "processing")
    tropo = Tropo::Generator.new
    tropo.say "Thanks for submitting your croon!"
    render :json => tropo.response
  end

  def hangup
    @croon.update_attributes(:hangup => true)
    tropo = Tropo::Generator.new
    tropo.stop_recording
    render :json => tropo.response
  end

  private

  def find_croon
    croon_id = begin
      sessions_object = Tropo::Generator.parse request.env['rack.input'].read

      sessions_object[:session][:parameters][:croon_id]
    rescue
      params[:croon_id]
    end
    @croon = Croon.criteria.id(croon_id).first
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def error_messages(errors)
    content_tag :span, errors.join(' and '), :class => 'error'
  end
end

app/helpers/croons_helper.rb
module CroonsHelper

  def song_select_options(songs)
    options = []
    songs.each do |s|
      options << [ "#{s.title} by #{s.artist}", s.id ]
    end
    options
  end

  def display_status(croon)
    exclamation = "Oh No!  "
    if croon.recording_filename
      "Click below to play your song!"
    else
      if croon.hangup
        case croon.status
          when "initialized" then
            exclamation + "Something unexpected happened!"
          when "calling" then
            exclamation + "The call was disconnected before the song started!"
          when "recording" then
            exclamation + "The call was disconnected before the song finished!  Be sure to either press '9' or wait for the song to end before hanging up."
          when "processing" then
            exclamation + "The call was disconnected before the song finished!  Be sure to either press '9' or wait for the song to end before hanging up."
          when "complete" then
            exclamation + "We were unable to process your file!  Please try again."
        end
      else
        case croon.status
          when "initialized" then
            "You should receive a phone call shortly if you haven't already!"
          when "calling" then
            "You should receive a phone call shortly if you haven't already!"
          when "recording" then
            "We're still recording.  You have great pipes!"
          when "processing" then
            "Congratulations!  You have submitted a song, but we haven't finished processing it.  Press 'Finish' again in a few seconds."
          when "complete" then
            exclamation + "We were unable to process your file!  Please try again."
        end
      end
    end
  end
end

app/helpers/tropo_recordings_helper.rb
module TropoRecordingsHelper
end

app/helpers/tropo_sessions_helper.rb
module TropoSessionsHelper
end

app/views/croons/_player.html.haml
%tr
  %td 
    %a{:href => (croon.recording.url || "http://croonstar-songs.s3.amazonaws.com/mjbilliejean.mp3"), :class =>"sm2_button"}
  %td= croon.song.title
  %td.small by
  %td= croon.crooner.present? ? croon.crooner : "Anonymous"

app/views/croons/create.html.erb
<h1>Croons#create</h1>
<p>Find me in app/views/croons/create.html.erb</p>

app/views/croons/index.html.haml
.instructions.span-24
  = form_for @croon do |f|
    .span-6.prepend-1.colborder
      = fields_for "croon[song_attributes]", @croon.song do |song_form|
        = song_form.label :id, "1. Select a Song"
        %br
        = song_form.select :id, song_select_options(@songs)
    .span-8.colborder
      = f.label :phone_number, "2. Tell us where to call you"
      %br
      = f.phone_field :phone_number, :size => 10
      =# error_messages(f.object.errors[:phone_number])
    .span-6.append-1.last
      %span 3. Croon!
      %br
      = f.submit 'Get Your Croon On'

%h2.list Most Popular
.prepend-6.span-12.append-6
  %table#croons
    %tbody
      - @croons.each do |croon|
        = render :partial => "player", :locals => {:croon => croon}
  = will_paginate @croons

app/views/croons/show.html.haml
%div
    #status= display_status(@croon)
    %br
    - if @croon.recording_filename
        .prepend-6.span-12.append-6
            %table#croons
                %tbody
                    = render :partial => "player", :locals => {:croon => @croon}
    - elsif !@croon.crooner && !@croon.hangup
        - form_for @croon do |f|
            = f.label :crooner, "When you are finished singing, enter your name or alias:"
            %br
            = f.text_field :crooner
            = f.submit "Finish!"
        OR
    -elsif !@croon.hangup
        = form_tag({:action => :show, :id => @croon.id}, {:method => :get}) do
            = label_tag :crooner, "Click here when you are finished singing: "
            = submit_tag "Finish!"
        OR
    = button_to "Try Again", croons_url, :method => :get
    %br
    %h2.lyrics= "Lyrics to #{@croon.song.title}"
    %pre.lyrics= @croon.song.lyrics

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title CroonStar
    = stylesheet_link_tag "screen", "application"
    /[if lt IE 8] <link rel="stylesheet" href="../blueprint/ie.css" type="text/css" media="screen, projection">
    %style{:media => "screen", :type => "text/css"}
      p, table, hr, .box { margin-bottom:25px; }
      \.box p { margin-bottom:10px; }
    = csrf_meta_tag
    = render :partial => "shared/soundmanager"
  %body
    .container
      .header.prepend-6.span-12.append-6.last
        = image_tag "logo.png", :size => "100x100", :style => "margin-bottom:-30px;"
        %h1.title CroonStar
      = yield

app/views/shared/_soundmanager.html.erb
<link rel="stylesheet" type="text/css" href="/soundmanager/mp3-player-button.css" />
<script type="text/javascript" src="/soundmanager/soundmanager2.js"></script>
<script type="text/javascript" src="/soundmanager/mp3-player-button.js"></script>

<script type="text/javascript">

soundManager.url = '/soundmanager/swf'; // directory where SM2 .SWFs live
soundManager.debugMode = false;

</script>

<!-- required -->
<!-- <link rel="stylesheet" type="text/css" href="/soundmanager/360player.css" /> -->

<!-- special IE-only canvas fix -->
<!--[if IE]><script type="text/javascript" src="soundmanager/excanvas.js"></script><![endif]-->

<!-- Apache-licensed animation library -->
<!-- <script type="text/javascript" src="soundmanager/berniecode-animator.js"></script> -->

<!-- the core stuff -->
<!-- <script type="text/javascript" src="/soundmanager/soundmanager2.js"></script> -->
<!-- <script type="text/javascript" src="/soundmanager/360player.js"></script> -->

<!-- configure it for your use -->
<!-- <script type="text/javascript">

soundManager.url = '/soundmanager/swf'; // directory where SM2 .SWFs live

// Note that SoundManager will determine and append the appropriate .SWF file to the URL,
// eg. /path/to/sm2-flash-movies/soundmanager2.swf automatically.

// Beta-ish HTML5 audio support (force-enabled for iPad), flash-free sound for Safari + Chrome. Enable if you want to try it!
// soundManager.useHTML5Audio = true;

// do this to skip flash block handling for now. See the flashblock demo when you want to start getting fancy.
soundManager.useFlashBlock = false;

// disable debug mode after development/testing..
// soundManager.debugMode = false;

// Option 1: Simple onload() + createSound() method

// soundManager.onload = function() {
//   // SM2 has loaded - now you can create and play sounds!
//   soundManager.createSound('helloWorld','/path/to/hello-world.mp3');
//   soundManager.play('helloWorld');
// };
//
// // Option 2 (better): More flexible onload() + createSound() method
//
// soundManager.onload = function() {
//   var mySound = soundManager.createSound({
//     id: 'aSound',
//     url: '/path/to/an.mp3'
//     // onload: [ event handler function object ],
//     // other options here..
//   });
//   mySound.play();
// }
//
// // Option 3 (best): onready() + createSound() methods, handle load/failure together:
//
// soundManager.onready(function() {
//   // check if SM2 successfully loaded..
//   if (soundManager.supported()) {
//     // SM2 has loaded - now you can create and play sounds!
//     var mySound = soundManager.createSound({
//       id: 'aSound',
//       url: '/path/to/an.mp3'
//       // onload: [ event handler function object ],
//       // other options here..
//     });
//     mySound.play();
//   } else {
//     // (Optional) Hrmm, SM2 could not start. Show an error, etc.?
//   }
// });

</script> -->

app/views/tropo_recordings/create.html.erb
<h1>TropoMp3s#create</h1>
<p>Find me in app/views/tropo_recordings/create.html.erb</p>